//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabel_Hotel
    {
        public int UserID { get; set; }
        public string Explanation { get; set; }
        public string Photo { get; set; }
        public int score { get; set; }
        public string HotelName { get; set; }
        public string HotelLocation { get; set; }
        public string HotelSeller { get; set; }
        public string UserName { get; set; }
    }
}
