//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Comments
    {
        public string UserName { get; set; }
        public string Comment { get; set; }
        public string HotelName { get; set; }
        public int Score { get; set; }
    }
}
